### ISSUE TITLE
Investigate explicitly specifying the parser

### ISSUE THREAD

**Issue by alwinb** [alwinb/url-specification#4]
Currently the relationship between the URL structure (called the URL Model in the spec) and the grammar is not made fully formal, leaving it up to the reader to infer the parse function from the grammar and the model. It may well be close enough to be fine, but it is something to investigate. 

I tried to avoid introducing machinery needed for rigorously specifying the parser, ie. using inductive datatypes and algebraic semantics, and went with a somewhat more loose approach. I was hoping that it'd keep things lighter and simpler. 

RFC 3986 does not define URIs as structures but as strings that conform to a given BNF. This leads to a similar looseness around the specification of their resolution algorithm which does work on structures. I don't think it's an issue there, it's more than clear enough. However WHATWG URLs are more complex, so the approach doesn't quite work here. 

The machinery exists and is well known, but the question is how much of that should be introduced, and if so, how, especially with accessibility and simplicity in mind. 

Comments and suggestions are appreciated!

**Comment by zamfofex** [comment]
Since, except for `authority`, the values of the tokens of URLs are all strings, and so are the values of the tokens of authorities, wouldn’t it make sense to simply specify that the grammar rules with the same name as the type of the tokens give the values for the tokens from what they match in the URL string?

Maybe a table could be formed explictly, if simply referring to the name of the token types or to the names of the rules is too awkward. Though given that the names seem to match 1–1, I think it look even more awkward to have a table.

**Comment by alwinb** [comment]
What I had in mind was to mark certain rules as 'token-rules', indicating that they should be converted to nodes in an AST (rather than collapse into a string, or be ignored). This is similar to what is done in for example the [Lezer] parser system by Marijn Haverbeke, which is very nice.  

To implement _something_ that works, isn't much of an issue. But I don't know exactly how to express it more neatly in a specification. It seems to require making much more of the theory of grammars and parsing explicit, which also is not ideal. 

[Lezer]: https://lezer.codemirror.net/docs/guide/#tokens
